package com.funi.security.mbg.dao;

import com.funi.security.mbg.dto.AuthorityResourceRel;
import com.funi.security.mbg.dto.AuthorityResourceRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorityResourceRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    long countByExample(AuthorityResourceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    int deleteByExample(AuthorityResourceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    int insert(AuthorityResourceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    int insertSelective(AuthorityResourceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    List<AuthorityResourceRel> selectByExample(AuthorityResourceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    AuthorityResourceRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AuthorityResourceRel record, @Param("example") AuthorityResourceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AuthorityResourceRel record, @Param("example") AuthorityResourceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthorityResourceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthorityResourceRel record);

	//自定义属性或方法
}