package com.funi.security.mbg.dao;

import com.funi.security.mbg.dto.RoleAuthorityRel;
import com.funi.security.mbg.dto.RoleAuthorityRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleAuthorityRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    long countByExample(RoleAuthorityRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    int deleteByExample(RoleAuthorityRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    int insert(RoleAuthorityRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    int insertSelective(RoleAuthorityRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    List<RoleAuthorityRel> selectByExample(RoleAuthorityRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    RoleAuthorityRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoleAuthorityRel record, @Param("example") RoleAuthorityRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoleAuthorityRel record, @Param("example") RoleAuthorityRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleAuthorityRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleAuthorityRel record);

	//自定义属性或方法
}