package com.funi.security.mbg.dao;

import com.funi.security.mbg.dto.UserRoleRel;
import com.funi.security.mbg.dto.UserRoleRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    long countByExample(UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    int deleteByExample(UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    int insert(UserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    int insertSelective(UserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    List<UserRoleRel> selectByExample(UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    UserRoleRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserRoleRel record, @Param("example") UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserRoleRel record, @Param("example") UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRoleRel record);

	//自定义属性或方法
}