package com.funi.security.mbg.dto;

import com.funi.security.supports.BasicDto;
import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table authority_resource_rel
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AuthorityResourceRel extends BasicDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * serialVersionUID 序列号 
     */
    private static final long serialVersionUID = 1L;

    /**
     * pk_id
     */
    private String id;

    /**
     * 权限id
     */
    private String authorityId;

    /**
     * 资源id
     */
    private String resourceId;

    /**
     * 得到pk_id
     * @return  pk_id
     */
    public String getId() {
        return id;
    }

    /**
     * 设置pk_id
     * @param id pk_id
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 得到权限id
     * @return  权限id
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * 设置权限id
     * @param authorityId 权限id
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }

    /**
     * 得到资源id
     * @return  资源id
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * 设置资源id
     * @param resourceId 资源id
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

	//自定义属性或方法
}