package com.funi.security.mbg.dto;

import com.funi.security.supports.BasicDto;
import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_authority_rel
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class RoleAuthorityRel extends BasicDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * serialVersionUID 序列号 
     */
    private static final long serialVersionUID = 1L;

    /**
     * pk_id
     */
    private String id;

    /**
     * 角色id
     */
    private String roleId;

    /**
     * 权限id
     */
    private String authoriryId;

    /**
     * 得到pk_id
     * @return  pk_id
     */
    public String getId() {
        return id;
    }

    /**
     * 设置pk_id
     * @param id pk_id
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 得到角色id
     * @return  角色id
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * 设置角色id
     * @param roleId 角色id
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * 得到权限id
     * @return  权限id
     */
    public String getAuthoriryId() {
        return authoriryId;
    }

    /**
     * 设置权限id
     * @param authoriryId 权限id
     */
    public void setAuthoriryId(String authoriryId) {
        this.authoriryId = authoriryId == null ? null : authoriryId.trim();
    }

	//自定义属性或方法
}