package com.funi.security.mbg.dto;

import com.funi.security.supports.BasicDto;
import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class User extends BasicDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * serialVersionUID 序列号 
     */
    private static final long serialVersionUID = 1L;

    /**
     * pk_id
     */
    private String id;

    /**
     * 用户登录名
     */
    private String userName;

    /**
     * 密码
     */
    private String password;

    /**
     * 用户真名
     */
    private String realName;

    /**
     * 电话
     */
    private String tel;

    /**
     * 邮箱
     */
    private String email;

    /**
     * 用户状态
     */
    private String statusType;

    /**
     * 是否管理员
     */
    private Boolean isAdmin;

    /**
     * 最后一次登录ip
     */
    private String lastLoginIp;

    /**
     * 最后一次登录时间
     */
    private Date lastLoginDate;

    /**
     * 最后一次修改密码时间
     */
    private Date lastPwdUpdateDate;

    /**
     * 备注
     */
    private String remark;

    /**
     * 得到pk_id
     * @return  pk_id
     */
    public String getId() {
        return id;
    }

    /**
     * 设置pk_id
     * @param id pk_id
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 得到用户登录名
     * @return  用户登录名
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 设置用户登录名
     * @param userName 用户登录名
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 得到密码
     * @return  密码
     */
    public String getPassword() {
        return password;
    }

    /**
     * 设置密码
     * @param password 密码
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * 得到用户真名
     * @return  用户真名
     */
    public String getRealName() {
        return realName;
    }

    /**
     * 设置用户真名
     * @param realName 用户真名
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * 得到电话
     * @return  电话
     */
    public String getTel() {
        return tel;
    }

    /**
     * 设置电话
     * @param tel 电话
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * 得到邮箱
     * @return  邮箱
     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置邮箱
     * @param email 邮箱
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 得到用户状态
     * @return  用户状态
     */
    public String getStatusType() {
        return statusType;
    }

    /**
     * 设置用户状态
     * @param statusType 用户状态
     */
    public void setStatusType(String statusType) {
        this.statusType = statusType == null ? null : statusType.trim();
    }

    /**
     * 得到是否管理员
     * @return  是否管理员
     */
    public Boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * 设置是否管理员
     * @param isAdmin 是否管理员
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * 得到最后一次登录ip
     * @return  最后一次登录ip
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * 设置最后一次登录ip
     * @param lastLoginIp 最后一次登录ip
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * 得到最后一次登录时间
     * @return  最后一次登录时间
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * 设置最后一次登录时间
     * @param lastLoginDate 最后一次登录时间
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * 得到最后一次修改密码时间
     * @return  最后一次修改密码时间
     */
    public Date getLastPwdUpdateDate() {
        return lastPwdUpdateDate;
    }

    /**
     * 设置最后一次修改密码时间
     * @param lastPwdUpdateDate 最后一次修改密码时间
     */
    public void setLastPwdUpdateDate(Date lastPwdUpdateDate) {
        this.lastPwdUpdateDate = lastPwdUpdateDate;
    }

    /**
     * 得到备注
     * @return  备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置备注
     * @param remark 备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	//自定义属性或方法
}